### ISSUE TITLE
redis 不是关系型数据库 是nosql

### ISSUE THREAD

**Issue by coderstory** [FrozenGEE/compose#8]
https://github.com/FrozenGEE/compose/blob/main/%5B03%5D%20%E7%BE%A4%E6%99%96%26%E6%96%B0%E7%BB%BF%E8%81%94/%5B%E7%BE%A4%E6%99%96%26%E6%96%B0%E7%BB%BF%E8%81%94%5D%20redis-%E5%85%B3%E7%B3%BB%E5%9E%8B%E6%95%B0%E6%8D%AE%E5%BA%93.yml

**Comment by FrozenGEE** [comment]
哦，好的，复制粘贴少了，是非关系型
