### ISSUE TITLE
moviepilot已发布2.0正式版，与V1的compose配置方式不一样，建议新增

### ISSUE THREAD

**Issue by fc525260** [FrozenGEE/compose#9]
2.0功能更加强大，内置目录监控。
不兼容V1，不支持升级覆盖安装，需要单独安装。改端口位置和文件存放路径可与V1共存。

**Comment by FrozenGEE** [comment]
> 2.0功能更加强大，内置目录监控。
> 不兼容V1，不支持升级覆盖安装，需要单独安装。改端口位置和文件存放路径可与V1共存。

我没搞2.0，好像要内测啥来着，并且，懒狗，等出来正式的再说吧。

**Comment by FrozenGEE** [comment]
写好了，没什么区别，放在了特殊版本的20里面
